exclude: "\\.snap$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json

  # python
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [--config, .flake8]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.4.1
    hooks:
      - id: sqlfluff-lint
        args: [--exclude-rules, "L008,L011,L031",
              --dialect, "clickhouse",
        ]
        # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']
      #- id: sqlfluff-fix
      #  args: [--exclude-rules, "L008,L011,L031",
      #        --dialect, "mysql",
      #  ]
